controllers:
    resource:
        path: ../src/Controller/
        namespace: App\Controller
    prefix: /api
    name_prefix: api_
    type: attribute

api_auth_login:
    path: /api/auth/login
    methods: ["POST"]